accounts:
  - name: gerald
    coins: ["100000000000000000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
validator:
  name: gerald
  staked: "100000000stake"
genesis:
  chain_id:"algo"
  app_state:
    staking:
      params:
        bond_denom:"stake"
